### PR TITLE
Feature - Deployment Config

### PR DESCRIPTION
**Pull request by four43**
To get some better testing I created some Terraform config to setup a Lambda with various triggers Mangum supports. I think I already found a bug to fix in Lambda@Edge support. This could be further expanded into a full end-to-end test at some point, but I figured it was nice to get a little environment set up so we can at least test things effectively.

### CODE REVIEW

**Comment by four43** [comment]
Man these API Gateways are junk. What a mess!

**Comment by jordaneremieff** [comment]
Hi @four43, thanks for the PR! 

I'm not very familiar with Terraform, so I'd like to get an understanding of how to use these scripts and what kind of maintenance might be required to keep them up-to-date, is there a way to automate testing them? 

Also, I'm wondering if it would be better to include these in a separate project that could be referenced in documentation. My main concern is around the maintenance burden of including specific deployment configurations as part of the main repo, especially if I am not using this tool myself, and I've generally included examples configurations for testing outside of the main project.

**Comment by four43** [comment]
Hey!

So think of these as a stepping stone to end-to-end tests. Testing them wouldn't really be an issue because you don't test your tests typically, but maintenance certainly. 

Since many of these transformers are basically assuming how messages looked based on documentation, I wanted something where I could actually really see what the messages were looking like. A cool end goal would be to actually have this whole thing automated and run by GitHub Actions or something. Use Terraform to spin up the infra, run tests against it and make sure you get back answers you were expecting, then tear it all down. Since this project could be multi-cloud, Terraform is a great tool for the job.

That's the end goal however, I was just poking around and seeing if I got the requests right so far and wanted to share what I found. It could also be a nice reference for users who are looking for a quick getting started. We could build on it more as needed. 

We use Terraform every day professionally/production capacity. I'd be happy to answer any additional questions you had. I encourage you to play with it a bit though, it's really slick.

Thanks!

**Comment by jordaneremieff** [comment]
@four43 thanks for explaining.

I think let's merge this, but could you add some more information to the included README.md along the lines of a quick start guide for myself and others to try these out?

**Pull request closed without merging**
