### PR TITLE
Feature events lambda at edge

### PR DESCRIPTION
**Pull request by four43**
I added basic functionality to handle Lambda@Edge events. This first set of commits were to just show off the functionality. I think the code could use some cleanup around how different strategies are chosen for each different type of event. If you're interested I can keep going, this was mainly to just get a discussion going around that functionality. I'm curious to hear what you think. Thanks!

### CODE REVIEW

**Comment by four43** [comment]
100% Test coverage! Whew, you guys don't mess around!

**Comment by jordaneremieff** [comment]
@four43 thanks for the PR, this is something we can include if you wish to continue - have you tested this in a deployment at this point?

I think the event handling strategy here should be discussed a bit to explore the options (specifically referring to the code [here](https://github.com/jordaneremieff/mangum/pull/167/files#diff-f2be8188d8c883ee01c8f4eb66255ae5a8f90c309e903f09efd9afff4c35b6d1R132)). What are you thoughts on using a configuration parameter instead of this approach, or is there a reliable way to determine which event type to use?

**Comment by four43** [comment]
Glad you're interested! The events actually look pretty different. Annoyingly so lol. 

Check out [this line](https://github.com/jordaneremieff/mangum/pull/167/files#diff-e52e4ddd58b7ef887ab03c04116e676f6280b824ab7469d5d3080e5cba4f2128R145) which shows the event has a "cf" (CloudFront) property the others don't.

Let me gather some docs with example events. I'd like to pull apart some of this parsing for these different environments. Just to clarify the goal of this is to support: 

 * API Gateway
 * HTTP Gateway
 * ALB (I didn't know this was an option until playing with your code!)
 * CloudFront (Lambda@Edge)

I really like this project. Common FastAPI/Flask code that will work wherever you want to put it without massive refactoring.

**Comment by four43** [comment]
Okay I have a good handle on how I want to break this apart. I have each handler split out into different classes to keep that logic separated. We can probably close PR, I'll have another one (it will be a big one though, restructuring a lot) that should clean stuff up now that there are more handlers.

**Pull request closed without merging**
